version: '2'

services:
  api:
    image: atzedevries/docker-nba-api:V2.4
    ports:
      - "8080:8080"
    links:
      - elasticsearch:es
    volumes:
      - /etc/nba/dwca:/etc/nba/dwca

  api-prev:
    image: atzedevries/docker-nba-api:V2.3
    ports:
      - "8081:8080"
    links:
      - elasticsearch:es
    volumes:
      - /etc/nba/dwca:/etc/nba/dwca


  elasticsearch:
    image: atzedevries/elasticsearch-s3:5.1.2
    environment:
      #should be half of system mem
      #xms must be same as xmx
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - /es-data:/usr/share/elasticsearch/data
    command: >
      elasticsearch
      -Ecluster.name="nba-cluster"
      -Enetwork.host="_site_"

  etl:
    image: atzedevries/docker-nba-etl:V2.4
    volumes:
      - /data/nba-import/data:/payload/data
      - /data/nba-import/log:/payload/software/log
    links:
      - elasticsearch:es
    restart: "no"

  kibana:
    image: kibana:5.1.2
    links:
      - elasticsearch:elasticsearch
    ports:
      - "5601:5601"

  minio:
    image: minio/minio
    command: server /export
    environment:
      # minimal 5 chars
      MINIO_ACCESS_KEY: piets
      # minimal 8 chars
      MINIO_SECRET_KEY: klaasklaas
    volumes:
      - /data/snapshots:/export
    ports:
      - "9000:9000"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      # default username is admin
      GF_SECURITY_ADMIN_PASSWORD: jan
    links:
      - elasticsearch:elasticsearch
